### PR TITLE
adding ML with Python section

### PR DESCRIPTION
**Pull request by redouanelg**
any modification or suggestion is welcomed

### CODE REVIEW

**Comment by lesommer** [comment]
looks good. Here is a couple of references and links you could consider including too : 
https://github.com/AlessandroMozzato/datasci_course_materials
https://www.youtube.com/watch?v=kgicutzlq50
machine learning with sk-learn, lecture https://www.youtube.com/watch?v=Cte8FYCpylk
machine learning for time series data in python https://www.youtube.com/watch?v=ZgHGCfwExw0
Machine Learning for Analyzing Complex Time Series https://www.youtube.com/watch?v=UxJB_5PyKTI

**Comment by lesommer** [comment]
you could also clean the section "Other useful python packages and jupyter notebooks" that mention some ML libs. thanks.

**Comment by redouanelg** [comment]
Done

**Comment by lesommer** [comment]
this looks good to me. Thanks @redouanelg

**Pull request merged**
